// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentRef } from "./ContentRef";
import type { ToolError } from "./ToolError";
import type { ToolModelPayload } from "./ToolModelPayload";
import type { ToolStatus } from "./ToolStatus";

export type ToolResult = { status: ToolStatus, summary: string, data: any, model: ToolModelPayload, output_ref?: ContentRef | null, error?: ToolError | null, };
