// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocInfo } from "./DocInfo";
import type { RoundBlock } from "./RoundBlock";
import type { RoundDeltaKind } from "./RoundDeltaKind";
import type { TaskInfo } from "./TaskInfo";
import type { ToolCallDef } from "./ToolCallDef";
import type { ToolResultDef } from "./ToolResultDef";
import type { TurnData } from "./TurnData";
import type { UsageInfo } from "./UsageInfo";

export type Agent2Ui = { "type": "turn_start", turn_id: string, user_text: string, } | { "type": "turn_end", turn_id: string, stop_reason?: string, usage?: UsageInfo, } | { "type": "round_delta", turn_id: string, round_num: number, kind: RoundDeltaKind, delta: string, } | { "type": "round_complete", turn_id: string, round_num: number, thinking?: string, answer?: string, tool_calls?: Array<ToolCallDef>, 
/**
 * Ordered blocks matching LLM output sequence (preferred).
 */
blocks?: Array<RoundBlock>, 
/**
 * true = this is the final round of the turn
 */
is_final: boolean, } | { "type": "tool_results", turn_id: string, round_num: number, results: Array<ToolResultDef>, } | { "type": "tool_exec_delta", tool_call_id: string, delta: string, } | { "type": "session_restored", seed: string, turns: Array<TurnData>, tokens_used: number, cache_hit_pct: number, 
/**
 * Total number of turns in this session.
 */
total_turns: number, 
/**
 * True if there are more (older) turns beyond what's sent.
 */
has_more: boolean, } | { "type": "more_turns", turns: Array<TurnData>, 
/**
 * True if there are still more (older) turns available.
 */
has_more: boolean, } | { "type": "session_created", seed: string, } | { "type": "snapshot", seed: string, 
/**
 * Current turns in this session (from last SessionRestored).
 */
turns?: Array<TurnData>, 
/**
 * Total tokens consumed.
 */
tokens_used: number, 
/**
 * Model context window limit.
 */
context_limit: number, 
/**
 * Events buffered since the frontend's last_seq.
 */
buffered_events?: Array<Agent2Ui>, 
/**
 * Current monotonic sequence id (latest event seq).
 */
seq_id: bigint, 
/**
 * True if ring buffer wrapped and some events were lost.
 */
has_more: boolean, } | { "type": "error", message: string, } | { "type": "tool_notice", message: string, 
/**
 * "warn" or "error"
 */
level: string, } | { "type": "balance", is_available: boolean, total_balance: string, currency: string, } | { "type": "dashboard", hp_connected: boolean, session_seed: string, tool_calls_total: number, tool_failures: number, current_phase: string, streaming: boolean, dsml_compat_count: number, documents?: Array<DocInfo>, recent_edits?: Array<string>, tasks?: Array<TaskInfo>, session_title?: string, usage?: UsageInfo, context_limit: number, model?: string, } | { "type": "done" } | { "type": "compact_start", turns_total: number, turns_keeping: number, } | { "type": "compact_end", summary_chars: number, turns_compacted: number, } | { "type": "compact_delta", delta: string, } | { "type": "cancelled" } | { "type": "shutdown_ack" } | { "type": "ready" } | { "type": "audit_record", tool_name: string, result_summary: string, success: boolean, } | { "type": "exec_progress", tool_call_id: string, stream: string, seq: bigint, chunk: string, } | { "type": "tool_call_preview", turn_id: string, round_num: number, index: number, id: string, name: string, args_so_far: string, } | { "type": "code_delta", lines_added: number, lines_removed: number, files_created: number, files_deleted: number, file?: string, };
