// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session metadata — unified persistence + runtime state.
 *
 * Fields marked `#[serde(skip)]` are runtime-only and not persisted to meta.json.
 */
export type SessionMeta = { seed: string, created_at: bigint, updated_at: bigint, model: string, effort?: string, message_count: number, 
/**
 * Number of conversation turns (one user query + its assistant/tool chain).
 */
turn_count: number, last_summary: string, 
/**
 * Number of earliest turns compacted (skipped in LLM context).
 */
compact_skip: number, 
/**
 * Agent operating mode: 0=Normal, 1=Plan, 2=Code.
 */
mode: number,
/**
 * True if this session has messages in the Turso SQLite store.
 */
turso_backed: boolean,
};
