// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillInfo } from "./SkillInfo";

/**
 * Payload for Agent2Ui::SkillsChanged.
 */
export type SkillsStatus = { 
/**
 * All discoverable skills in the workspace.
 */
available: Array<SkillInfo>, 
/**
 * Names of currently loaded (explicit, $mention-activated) skills.
 */
active: Array<string>, };
