// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Ui2Agent = { "type": "user_input", text: string, } | { "type": "tool_call", id: string, name: string, action: string, args: any, } | { "type": "create_session" } | { "type": "cancel" } | { "type": "shutdown" } | { "type": "reload_config" } | { "type": "undo_turn", turn_id: string, } | { "type": "compact" } | { "type": "resume_session", seed: string, } | { "type": "new_session" } | { "type": "load_more_turns", 
/**
 * Load turns older than this turn_id.
 */
before_turn_id: string, 
/**
 * How many turns to load.
 */
count: number, } | { "type": "subscribe", seed: string, } | { "type": "reconnect", seed: string, last_seq: bigint, } | { "type": "ask_response", answer: string, };
