// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 能力名称（PLAN 固定命名）。
 */
export type CapabilityName = "ringing_v2" | "ringing_batch_v2" | "ringing_bootstrap_v2" | "ringing_command_status_v2";
