// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskAnswer } from "./AskAnswer";

/**
 * Control 频道命令。
 */
export type ControlCommand = { "type": "session_create", close_current: boolean, } | { "type": "session_resume", seed: string, } | { "type": "session_close", seed: string, } | { "type": "session_shutdown" } | { "type": "agent_reload_config" } | { "type": "interaction_ask_respond", interaction_id: string, answers: Array<AskAnswer>, } | { "type": "interaction_ask_dismiss", interaction_id: string, } | { "type": "plan_review_respond", interaction_id: string, approved: boolean, message?: string | null, autonomous: boolean, } | { "type": "skills_activate", name: string, } | { "type": "skills_release", name: string, } | { "type": "skills_reload" };
