// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 大内容外置引用（工具完整输出、超大 diff、诊断内容等）。
 * 事件只携带可渲染 tail / 统计信息与 `content_ref`；完整内容经鉴权 HTTP 按需读取。
 */
export type ContentRef = { content_id: string, media_type: string, sha256: string, truncated: boolean, };
