// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationMode } from "./ConversationMode";
import type { ImageBlock } from "./ImageBlock";

/**
 * Conversation 频道命令。
 */
export type ConversationCommand = { "type": "conversation_send_message", text: string, images?: Array<ImageBlock>, } | { "type": "conversation_cancel", turn_id?: string | null, } | { "type": "conversation_undo_turn", turn_id: string, } | { "type": "conversation_compact", turn_id?: string | null, } | { "type": "conversation_load_more", before_turn_id: string, count: number, } | { "type": "conversation_set_mode", mode: ConversationMode, };
