// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 会话工作模式（legacy `SetMode` 语义）。
 */
export type ConversationMode = "normal" | "plan" | "code";
