// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineIntent } from "./TimelineIntent";
import type { WorkerDirection } from "./WorkerDirection";

/**
 * Worker → daemon Ringing V1 timeline intent. It is intentionally distinct
 * from the per-channel `RingingWorkerEventEnvelope`.
 */
export type RingingTimelineIntentEnvelope = { schema: string, version: number, wire: string, direction: WorkerDirection, seed: string, intent_id: string, causation_id?: string | null, intent: TimelineIntent, };
