// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RingingChannel } from "./RingingChannel";
import type { RingingEvent } from "./RingingEvent";

/**
 * 事件批次（main→renderer 必须整 batch 传递，禁止展开为逐事件）。
 */
export type RingingEventBatch = { channel: RingingChannel, seed: string, from_stream_seq: bigint, to_stream_seq: bigint, state_revision?: bigint | null, events: Array<RingingEvent>, };
