// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Delivery } from "./Delivery";
import type { RingingChannel } from "./RingingChannel";
import type { RingingEvent } from "./RingingEvent";

/**
 * 事件信封（PLAN 固定字段）。
 */
export type RingingEventEnvelope = { schema: string, version: number, channel: RingingChannel,
/**
 * 可靠性等级：由领域事件定义显式声明，wire 不决定。
 */
delivery: Delivery,
/**
 * daemon 重启纪元；epoch 变化后 stream_seq 重置。
 */
server_epoch: string,
/**
 * 会话标识。
 */
seed: string,
/**
 * 每 (server_epoch, channel) 全局递增，供单条 SSE 连接恢复。
 */
stream_seq: number,
/**
 * 每 (seed, channel) 递增，供领域状态乱序检测。
 */
channel_seq: number,
/**
 * 每 session/channel 因果序（保留 legacy session_seq 语义）。
 */
session_seq: number,
/**
 * 事件唯一 id；同 id 至少一次投递但只允许应用一次（幂等）。
 */
event_id: string,
/**
 * 因果来源（如 command_id），用于关联命令与业务终态。
 */
causation_id?: string | null,
/**
 * 关联链 id。
 */
correlation_id?: string | null,
/**
 * 领域状态修订号；terminal 到达后旧 revision 的 replaceable 立即作废。
 */
state_revision?: number | null, event: RingingEvent, };
