// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RingingChannel } from "./RingingChannel";
import type { RingingCommand } from "./RingingCommand";
import type { WorkerDirection } from "./WorkerDirection";

/**
 * daemon → worker 命令 frame。
 */
export type RingingWorkerCommandEnvelope = { schema: string, version: number, 
/**
 * 线格式判别字段，固定 `WIRE_RINGING_DOMAIN_V1`。
 */
wire: string, direction: WorkerDirection, channel: RingingChannel, seed: string, command_id: string, command: RingingCommand, };
