// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RingingChannel } from "./RingingChannel";
import type { RingingEvent } from "./RingingEvent";
import type { WorkerDirection } from "./WorkerDirection";

/**
 * worker → daemon 事件 frame。
 */
export type RingingWorkerEventEnvelope = { schema: string, version: number, 
/**
 * 线格式判别字段，固定 `WIRE_RINGING_DOMAIN_V1`。
 */
wire: string, direction: WorkerDirection, channel: RingingChannel, seed: string, event_id: string, event: RingingEvent, };
