// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RingingChannel } from "./RingingChannel";
import type { RingingEvent } from "./RingingEvent";
import type { WorkerDirection } from "./WorkerDirection";

/**
 * worker → daemon 事件 frame。
 */
export type RingingWorkerEventEnvelope = { schema: string, version: number,
/**
 * 线格式判别字段，固定 `WIRE_RINGING_DOMAIN_V2`。
 */
wire: string, direction: WorkerDirection, channel: RingingChannel, seed: string, event_id: string,
/**
 * 因果来源 command_id（Ringing 命令执行期间产出的事件携带）。
 */
causation_id?: string | null, event: RingingEvent, };
