// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineFailure } from "./TimelineFailure";
import type { TimelineRound } from "./TimelineRound";
import type { TimelineTurnState } from "./TimelineTurnState";

export type TimelineTurn = { turn_id: string, user_text: string, sealed: boolean, state: TimelineTurnState, failure?: TimelineFailure | null, rounds: Array<TimelineRound>, };
