// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentRef } from "./ContentRef";

/**
 * 工具执行结果。
 */
export type ToolResult = { success: boolean,
/**
 * 可渲染摘要/tail。
 */
summary: string,
/**
 * 完整输出引用（≥10 MiB 或按内容策略外置）。
 */
output_ref?: ContentRef | null, };
