// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * frame 方向（stdin 只承载 Command，stdout 只承载 Event；stderr 只承载脱敏日志）。
 */
export type WorkerDirection = "command" | "event";
