allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
minimumReleaseAgeExclude:
  - electron
  - electron-vite
  - '@solidjs/web@2.0.0-beta.28'
  - solid-js@2.0.0-beta.28
  - vite-plugin-solid@3.0.0-next.18 || 3.0.0-next.20
  - '@dom-expressions/babel-plugin-jsx@0.50.0-next.33'
  - '@dom-expressions/compiler-darwin-arm64@0.50.0-next.33'
  - '@dom-expressions/compiler-darwin-x64@0.50.0-next.33'
  - '@dom-expressions/compiler-linux-arm64-gnu@0.50.0-next.33'
  - '@dom-expressions/compiler-linux-x64-gnu@0.50.0-next.33'
  - '@dom-expressions/compiler-wasm32-wasi@0.50.0-next.33'
  - '@dom-expressions/compiler-win32-x64-msvc@0.50.0-next.33'
  - '@dom-expressions/compiler@0.50.0-next.33'
  - '@solidjs/signals@2.0.0-beta.28'
  - babel-preset-solid@2.0.0-beta.28
  - jsdom@30.0.1
