// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCall } from "./ToolCall";
import type { UsageInfo } from "./UsageInfo";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Agent → UI frames (mpsc channel / stdout pipe in headless mode).
 */
export type Agent2Ui = { "type": "content_delta", delta: string, reasoning: string | null, } | { "type": "tool_progress", id: string, content: string, stream_type: string, } | { "type": "api_response", content: string, reasoning_content: string | null, tool_calls: Array<ToolCall> | null, stop_reason: string | null, usage: UsageInfo | null, 
/**
 * Full context token count (system + tools + messages).
 */
context_tokens: number, context_limit: number, session_tokens: bigint, } | { "type": "ask_user", id: string, question: string, options: Array<string> | null, } | { "type": "phase_changed", phase: string, } | { "type": "tool_state", explored: boolean, declared_files: Array<string>, read_files: Array<string>, written_this_turn: Array<string>, } | { "type": "done" } | { "type": "cancelled" } | { "type": "error", message: string, } | { "type": "cache_prediction", hit_rate: number, } | { "type": "shutdown_ack" } | { "type": "tool_result", id: string, name: string, content: string, success: boolean, args: string | null, } | { "type": "session_restored", seed: string, message_count: bigint, summary: string, tokens_used: number, cache_hit_pct: number, } | { "type": "debug_snapshot", hp_connected: boolean, session_seed: string, context_tokens: number, tool_calls_total: number, tool_failures: number, current_phase: string, streaming: boolean, dsml_compat_count: number, } | { "type": "balance", is_available: boolean, total_balance: string, currency: string, };

/**
 * UI → Agent frames (mpsc channel / stdin pipe in headless mode).
 */
export type Ui2Agent = { "type": "user_input", text: string, } | { "type": "tool_call", id: string, name: string, action: string, args: JsonValue, } | { "type": "set_phase", phase: string, } | { "type": "cancel" } | { "type": "shutdown" } | { "type": "debug_cmd", cmd: string, } | { "type": "set_auto_mode", auto_mode: boolean, };
